networks:
  spring-mysql:
    driver: bridge
  nginx-spring:
    driver: bridge

services:
  nginx:
    networks:
      - nginx-spring
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .nginx/.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_healthy

  db:
    networks:
      - spring-mysql
    expose:
      - "3306"
    restart: unless-stopped
    image: mysql:8.0
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 5

  app:
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health >/dev/null 2>&1 || exit 1" ]
      interval: 30s
      timeout: 4s
      retries: 5
      start_period: 60s
    expose:
      - "8080"
    networks:
      - nginx-spring
      - spring-mysql
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "127.0.0.1:8080:8080"

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: